services:
  # Map handler service
  mapgen:
    image: ghcr.io/marekvonrogall/mapgen/mapgen:latest
    environment:
      - MAPGEN_PORT=5001
      - IMGGEN_URL=http://imggen:5000
    networks:
      - bingo-net
    restart: unless-stopped

  # Image generation service
  imggen:
    image: ghcr.io/marekvonrogall/mapgen/imggen:latest
    environment:
      - IMGGEN_PORT=5000
    networks:
      - bingo-net
    volumes:
      - imggen-public:/app/public
    restart: unless-stopped

volumes:
  imggen-public:
    external: true
networks:
  bingo-net:
    external: true
