services:
  # Map handler service
  mapgen:
    build:
      context: ./src/MapService

  # Image generation service
  imggen:
    build:
      context: ./src/ImageService
    volumes:
      - imggen-public:/app/public

  # NGINX API Gateway
  nginx:
    build:
      context: ./src/nginx
    ports:
      - "8080:80"
    depends_on:
      - mapgen
      - imggen
    volumes:
      - imggen-public:/app/public

volumes:
  imggen-public:
