name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Set Timeout for Docker Push
        run: |
          export DOCKER_CLIENT_TIMEOUT=800
          export COMPOSE_HTTP_TIMEOUT=800
          
      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose-build.yml build

      - name: Push Docker Image to GHCR
        run: |
          docker-compose -f docker-compose-build.yml push

  deploy:
    name: Deploy to Droplet
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload Deployment Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          target: /root/deployment/
          source: |
            ./docker-compose-deploy.yml
            ./src/nginx/nginx.conf

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/deployment
            docker-compose pull
            docker-compose down
            docker-compose up -d