name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_ACCESS_TOKEN }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
      - name: Set Timeout for Docker Push
        run: |
          export DOCKER_CLIENT_TIMEOUT=800
          export COMPOSE_HTTP_TIMEOUT=800
          
      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose-build.yml build

      - name: Push Docker Image to GHCR
        run: |
          docker-compose -f docker-compose-build.yml push

  deploy:
    name: Deploy to Droplet
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check if deployment files exist
        run: |
          ls -l ./docker-compose-deploy.yml
          ls -l ./src/nginx/nginx.conf

      - name: Create /root/deployment directory
        run: |
          sudo apt-get install sshpass
          sshpass -p "${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "mkdir -p /root/deployment"

      - name: Upload Deployment Files
        run: |
          sshpass -p "${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}" scp -o StrictHostKeyChecking=no ./docker-compose-deploy.yml root@${{ secrets.DROPLET_IP }}:/root/deployment/
          sshpass -p "${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}" scp -o StrictHostKeyChecking=no ./src/nginx/nginx.conf root@${{ secrets.DROPLET_IP }}:/root/deployment/

      - name: Deploy Application
        run: |
          sshpass -p "${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << "EOF"
            cd /root/deployment
            docker-compose pull
            docker-compose down
            docker-compose up -d
          EOF"